###############################################
# common configuration for ALL branches
###############################################


configuration: Debug
image: Visual Studio 2017
version: 0.0.0.{build}

init:
  - git config --global core.autocrlf input
    
    
    # clone directory
clone_folder: c:\projects\footballpredictiongame

environment:
    APPVEYORAPI:
      secure: 7Ed84TRzcrSQ8auippk9StbaLhigsturtNPiSEi/MLU=
    nuget_user: developer@ssatuk.co.uk
    nuget_password:
      secure: 0LMdkuBPbT5J2yZZuyZBkQ==
    PSAzureRMLabTool_TENANTID: c5263ca1-a2e1-42fd-81bb-effcd1666efd
    PSAzureRMLabTool_APPID: fb08c8bf-7b34-4456-9895-afb8ae32db30 
    PSAzureRMLabTool_APPSECRET:
      secure: BQBWZeADInqcS8WdQcuth6xWzEAOhZeucXFrRaG998H+edthnZxoSzFsA5BO8qFP	
    DEFAULT_AZURE_SUBSCRIPTION:
      secure: veOQseWW9zf/blP9eyO57t/D0h7I3mgvXpzGB9zGfGuuBid4QSyEKyrVfrssXwFw
    SQLLOGIN:
      secure: khOVM+y/C1H0yHRU3mV2iQ==
    SQLPASS:
      secure: hV4z8fO+uqRiRFi7Uzw0Hg==
    RESOURCEGROUP: football2018

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root but will reset it if packages.config is modified

# scripts that run after cloning repository
install:
   - cmd: git submodule update --init --recursive
   - ps: Invoke-WebRequest http://cakebuild.net/download/bootstrapper/windows -OutFile build.ps1
   - ps: ./build.ps1  -Verbose -Target "Transform" -ScriptArgs '--settings_skipverification=true'
   # if the commit message includes #AZURERM run a resource deployment, 
   # using sql parameters from environment defined above
   - ps: >-
       if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -like '*#AZURERM*'){
         Write-Host $env:APPVEYOR_REPO_COMMIT_MESSAGE
         Write-Host "Calling build task for AzureRM"
         ./build.ps1  -Verbose -Target "AzureRM" -ScriptArgs '--settings_skipverification=true'
       } else {
         Write-Host $env:APPVEYOR_REPO_COMMIT_MESSAGE
         Write-Host "Skipping build task for AzureRM"
       }
       
   - nuget sources add -Name SSATFeed -Source https://ci.appveyor.com/nuget/julianelve-2wugvm77ww7n -UserName %nuget_user% -Password %nuget_password
   - nuget restore

#---------------------------------#
#       build configuration       #
#---------------------------------#
build:
  project: FootballPredictionGame.sln      # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy

  # MSBuild verbosity level
  verbosity: minimal


# scripts to run before build
before_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off


#---------------------------------#
#       test  configuration       #
#---------------------------------#

test:
  categories:
    except:
      - skip_appveyor

#----------------------------------------------------------------#
#       deployment configuration                                 #
#                                                                #
# to only deploy from master branch move this section            # 
# into the into the master branch override section of this file  #
# (remember to fix the indents correctly)                        #
#----------------------------------------------------------------#

deploy:
    - provider: WebDeploy
      server: https://football2018.scm.azurewebsites.net:443/msdeploy.axd?site=football2018
      website: football2018
      username: $football2018
      password:
        secure: DUa7R7vOdfehQyiuPUQGu0VsYHc+mXx7MyXPLe4XtbUdMGdANkN0iTy+CxFVa6zQncfV8LfW8TxtUkgmzr/iWQ==
      ntlm: false
      remove_files: true
      artifact: FootballPredictionGame.zip


#---------------------------------#
#       Notifications             #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://outlook.office.com/webhook/7edad36f-cee4-497e-9af5-ca8f28fdc544@c5263ca1-a2e1-42fd-81bb-effcd1666efd/IncomingWebhook/d5a133f68fa843769577e831721be08e/486dadbf-58e0-4c8e-8922-df63ee598066
    method: POST
    content_type: application/json
    body: >-
      {
          "title": "AppVeyor Build {{#passed}}passed{{/passed}}{{#failed}}failed{{/failed}}",
          "summary": "Build {{projectName}} {{buildVersion}} {{status}}",
          "themeColor": "{{#passed}}00FF00{{/passed}}{{#failed}}FF0000{{/failed}}",
          "sections": [
              {
                  "activityTitle": "{{commitAuthor}} on {{commitDate}} ( {{repositoryProvider}}/{{repositoryName}} )",
                  "activityText": "[Build {{projectName}} {{buildVersion}} {{status}}]({{buildUrl}})"
              },
              {
                  "title": "Details",
                  "facts": [
                      {
                          "name": "Commit",
                          "value": "[{{commitId}} by {{commitAuthor}} on {{branch}} at {{commitDate}}]({{commitUrl}})"
                      },
                      {
                          "name": "Message",
                          "value": "{{commitMessage}}"
                      },
                      {
                          "name": "Duration",
                          "value": "{{duration}} ({{started}} - {{finished}})"
                      }
                  ]
              }
          ]
      }
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

# here we are going to override common configuration - note indents
for:
#################################################################################################################
# override settings for `master` branch
#################################################################################################################
 
-
  branches:
    only:
      - master

  configuration: Release
